// Archive data configuration
const ARCHIVE_ITEMS = [
    {
      id: 1,
      title: "Naori (2023)",
      image: "./img/car/naori.jpg",
      characters: ["Naori"],
      project: "Birth by Memory",
      background: "Pink Background",
      filters: ["Safe"],
      furColor: "Brown",
      species: ["Fox"],
      gender: ["Female"],
      bodyType: ["Flat Chested"],
      createdDate: "November 26 2023",
      mirrors: [{ platform: "furaffinity", url: "https://www.furaffinity.net/view/57439158/" }],
      tags: ["Raster Art"],
    },
    {
        id: 2,
        title: "Too Hot Comic (v1)",
        image: "./img/car/sera22.jpg",
        characters: ["Sera"],
        project: "Birth by Memory",
        background: "Gray Background",
        filters: ["Safe"],
        furColor: [],
        species: ["Fox"],
        gender: ["Female"],
        bodyType: [],
        createdDate: "January 27, 2023",
        mirrors: [{ platform: "furaffinity", url: "https://www.furaffinity.net/view/57439245/" },
        { platform: "instagram", url: "https://www.instagram.com/p/Cn7bdRkJ4OO/" }],
        tags: ["Comic", "Raster Art", "Black & White"],
    },
    {
        id: 3,
        title: "Elaine (Concept)",
        image: "./img/car/lion.jpg",
        characters: ["Elaine"],
        project: "Untitled Project",
        background: "Gray Background",
        filters: ["Safe"],
        furColor: ["Yellow"],
        species: ["Lion"],
        gender: ["Female"],
        bodyType: [],
        createdDate: "July 16, 2025.",
        mirrors: [{ platform: "furaffinity", url: "https://www.furaffinity.net/view/61600438/" },
        { platform: "instagram", url: "https://www.instagram.com/p/DMMA1CDJ1JN/" }],
        tags: ["Crop Top", "Raster Art"],
    },
    {
        id: 4,
        title: "Stacy (Concept B)",
        image: "./img/3.jpg",
        characters: ["Stacy"],
        project: "Untitled Project",
        background: "Gray Background",
        filters: ["Safe"],
        furColor: ["Orange"],
        species: ["Cat"],
        gender: ["Female"],
        bodyType: ["Flat Chested"],
        createdDate: "June 26, 2025.",
        mirrors: [{ platform: "furaffinity", url: "https://www.furaffinity.net/view/61368298/" },
        { platform: "instagram", url: "https://www.instagram.com/p/DLYGOT1psej/" }],
        tags: ["Turtleneck", "Raster Art"],
    },
    {
        id: 5,
        title: "Stacy (Concept A)",
        image: "./img/dora.jpg",
        characters: ["Stacy"],
        project: "Untitled Project",
        background: "Gray Background",
        filters: ["Safe"],
        furColor: [],
        species: ["Cat"],
        gender: ["Female"],
        bodyType: ["Flat Chested"],
        createdDate: "June 21, 2025.",
        mirrors: [{ platform: "instagram", url: "https://www.instagram.com/p/DLYGOT1psej/" }],
        tags: ["Turtleneck", "Traditional Art"],
    },
    {
        id: 6,
        title: "Stacy (Concept D)",
        image: "./img/car/stacy.jpg",
        characters: ["Stacy"],
        project: "Untitled Project",
        background: "Rendered Background",
        filters: ["Safe"],
        furColor: ["Orange"],
        species: ["Cat"],
        gender: ["Female"],
        bodyType: ["Flat Chested"],
        createdDate: "July 11, 2025.",
        mirrors: [{ platform: "furaffinity", url: "https://www.furaffinity.net/view/61622527/"}],
        tags: ["Raster Art"],
    },
    {
        id: 7,
        title: "Stacy (Concept C)",
        image: "./img/car/conceptC.jpg",
        characters: ["Stacy"],
        project: "Untitled Project",
        background: "White Background",
        filters: ["Safe"],
        furColor: ["Orange"],
        species: ["Cat"],
        gender: ["Female"],
        bodyType: ["Flat Chested"],
        createdDate: "July 9, 2025.",
        mirrors: [{ platform: "furaffinity", url: "https://www.furaffinity.net/view/61622785/"}],
        tags: ["Raster Art"],
    },
    {
        id: 8,
        title: "Leo (2022)",
        image: "./img/car/leo.jpg",
        characters: ["Leo"],
        project: "Untitled Project",
        background: "Gray Background",
        filters: ["Safe"],
        furColor: [],
        species: ["Cat"],
        gender: ["Male"],
        bodyType: ["Flat Chested"],
        createdDate: "September 19, 2022.",
        mirrors: [{ platform: "furaffinity", url: "https://www.furaffinity.net/view/61622785/"}],
        tags: ["Raster Art", "Black & White"],
    },
    {
        id: 9,
        title: "Zsasz (2021)",
        image: "./img/car/zsasz2.jpg",
        characters: ["Zsasz"],
        project: null,
        background: "Gray Background",
        filters: ["Safe"],
        furColor: [],
        species: ["Hyena"],
        gender: ["Male"],
        bodyType: ["Flat Chested"],
        createdDate: "December 9, 2021.",
        mirrors: [{ platform: "furaffinity", url: "https://www.furaffinity.net/view/57584718/"}],
        tags: ["Raster Art"],
    },
    {
        id: 10,
        title: "A Deal With Satan",
        image: "./img/car/satan.jpg",
        characters: ["Eun-byul"],
        project: "Eun-byul (Comic)",
        background: "White Background",
        filters: ["Safe"],
        furColor: [],
        species: ["Hyena"],
        gender: ["Female"],
        bodyType: [],
        createdDate: "April 9, 2025.",
        mirrors: [{ platform: "furaffinity", url: "https://www.furaffinity.net/view/60518849/"}],
        tags: ["Raster Art", "Comic", "Button-Up", "Black & White"],
    },
    {
        id: 11,
        title: "Welcome Gate",
        image: "./img/car/comicB.jpg",
        characters: ["Eun-byul"],
        project: "Eun-byul (Comic)",
        background: "White Background",
        filters: ["Safe"],
        furColor: [],
        species: ["Hyena"],
        gender: ["Female"],
        bodyType: [],
        createdDate: "March 30, 2025.",
        mirrors: [{ platform: "furaffinity", url: "https://www.furaffinity.net/view/60391986/"}],
        tags: ["Raster Art", "Comic", "Button-Up", "Black & White"],
    },
  ]
  