// Archive data configuration
const ARCHIVE_ITEMS = [
    {
      id: 1,
      title: "Naori (2023)",
      image: "./img/car/naori.jpg",
      characters: ["Naori"],
      project: "Birth by Memory",
      background: "Pink Background",
      filters: ["Safe"],
      furColor: "Brown",
      species: ["Fox"],
      gender: ["Female"],
      bodyType: ["Flat Chested"],
      createdDate: "November 26 2023",
      mirrors: [{ platform: "furaffinity", url: "https://www.furaffinity.net/view/57439158/" }],
      tags: ["Raster Art", "Procreate", "Yellow Eyes"],
    },
    {
        id: 2,
        title: "Too Hot Comic (v1)",
        image: "./img/car/sera22.jpg",
        characters: ["Sera"],
        project: "Birth by Memory",
        background: "Gray Background",
        filters: ["Safe"],
        furColor: [],
        species: ["Fox"],
        gender: ["Female"],
        bodyType: [],
        createdDate: "January 27, 2023",
        mirrors: [{ platform: "furaffinity", url: "https://www.furaffinity.net/view/57439245/" },
        { platform: "instagram", url: "https://www.instagram.com/p/Cn7bdRkJ4OO/" }],
        tags: ["Comic", "Raster Art", "Black & White", "Procreate", "Bra", "Arm Warmer", "Neck Collar"],
    },
    {
        id: 3,
        title: "Elaine (Concept)",
        image: "./img/car/lion.jpg",
        characters: ["Elaine"],
        project: "Untitled Project",
        background: "Gray Background",
        filters: ["Safe"],
        furColor: ["Yellow"],
        species: ["Lion"],
        gender: ["Female"],
        bodyType: [],
        createdDate: "July 16, 2025",
        mirrors: [{ platform: "furaffinity", url: "https://www.furaffinity.net/view/61600438/" },
        { platform: "instagram", url: "https://www.instagram.com/p/DMMA1CDJ1JN/" }],
        tags: ["Crop Top", "Raster Art", "Procreate", "Yellow Eyes"],
    },
    {
        id: 4,
        title: "Stacy (Concept B)",
        image: "./img/3.jpg",
        characters: ["Stacy"],
        project: "Untitled Project",
        background: "Gray Background",
        filters: ["Safe"],
        furColor: ["Orange"],
        species: ["Cat"],
        gender: ["Female"],
        bodyType: ["Flat Chested", "Freckles"],
        createdDate: "June 26, 2025",
        mirrors: [{ platform: "furaffinity", url: "https://www.furaffinity.net/view/61368298/" },
        { platform: "instagram", url: "https://www.instagram.com/p/DLYGOT1psej/" }],
        tags: ["Turtleneck", "Raster Art", "Procreate"],
    },
    {
        id: 5,
        title: "Stacy (Concept A)",
        image: "./img/dora.jpg",
        characters: ["Stacy"],
        project: "Untitled Project",
        background: "Gray Background",
        filters: ["Safe"],
        furColor: [],
        species: ["Cat"],
        gender: ["Female"],
        bodyType: ["Flat Chested"],
        createdDate: "June 21, 2025",
        mirrors: [{ platform: "instagram", url: "https://www.instagram.com/p/DLYGOT1psej/" }],
        tags: ["Turtleneck", "Traditional Art", "Gray Eyes"],
    },
    {
        id: 6,
        title: "Stacy (Concept D)",
        image: "./img/car/stacy.jpg",
        characters: ["Stacy"],
        project: "Untitled Project",
        background: "Rendered Background",
        filters: ["Safe"],
        furColor: ["Orange"],
        species: ["Cat"],
        gender: ["Female"],
        bodyType: ["Flat Chested", "Spotted", "Body Stripes"],
        createdDate: "July 11, 2025",
        mirrors: [{ platform: "furaffinity", url: "https://www.furaffinity.net/view/61622527/"}],
        tags: ["Raster Art", "Procreate", "Pink Eyes"],
    },
    {
        id: 7,
        title: "Stacy (Concept C)",
        image: "./img/car/conceptC.jpg",
        characters: ["Stacy"],
        project: "Untitled Project",
        background: "White Background",
        filters: ["Safe"],
        furColor: ["Orange"],
        species: ["Cat"],
        gender: ["Female"],
        bodyType: ["Flat Chested", "Freckles", "Face Stripes"],
        createdDate: "July 9, 2025",
        mirrors: [{ platform: "furaffinity", url: "https://www.furaffinity.net/view/61622785/"}],
        tags: ["Raster Art", "Procreate", "Pink Eyes"],
    },
    {
        id: 8,
        title: "Leo (2022)",
        image: "./img/car/leo.jpg",
        characters: ["Leo"],
        project: "Birth by Memory",
        background: "Gray Background",
        filters: ["Safe"],
        furColor: ["White"],
        species: ["Cat"],
        gender: ["Male"],
        bodyType: ["Flat Chested", "Shoulder Muscles"],
        createdDate: "September 19, 2022",
        mirrors: [{ platform: "furaffinity", url: "https://www.furaffinity.net/view/61622785/"}],
        tags: ["Raster Art", "Black & White", "Procreate"],
    },
    {
        id: 9,
        title: "Zsasz (2021)",
        image: "./img/car/zsasz2.jpg",
        characters: ["Zsasz"],
        project: null,
        background: "Gray Background",
        filters: ["Safe"],
        furColor: [],
        species: ["Hyena"],
        gender: ["Male"],
        bodyType: ["Flat Chested", "Spotted"],
        createdDate: "December 9, 2021",
        mirrors: [{ platform: "furaffinity", url: "https://www.furaffinity.net/view/57584718/"}],
        tags: ["Raster Art", "Photopea", "Purple Eyes"],
    },
    {
        id: 10,
        title: "A Deal With Satan",
        image: "./img/car/satan.jpg",
        characters: ["Eun-byul"],
        project: "Eun-byul (Comic)",
        background: "White Background",
        filters: ["Safe"],
        furColor: [],
        species: ["Hyena"],
        gender: ["Female"],
        bodyType: ["Spotted", "Shoulder Muscles"],
        createdDate: "April 9, 2025",
        mirrors: [{ platform: "furaffinity", url: "https://www.furaffinity.net/view/60518849/"}],
        tags: ["Raster Art", "Comic", "Button-Up", "Black & White", "Procreate", "Bandana"],
    },
    {
        id: 11,
        title: "Welcome Gate",
        image: "./img/car/ComicB.jpg",
        characters: ["Eun-byul"],
        project: "Eun-byul (Comic)",
        background: "White Background",
        filters: ["Safe"],
        furColor: [],
        species: ["Hyena"],
        gender: ["Female"],
        bodyType: ["Spotted", "Shoulder Muscles"],
        createdDate: "March 30, 2025",
        mirrors: [{ platform: "furaffinity", url: "https://www.furaffinity.net/view/60391986/"}],
        tags: ["Raster Art", "Comic", "Button-Up", "Black & White", "Procreate", "Bandana"],
    },
    {
        id: 12,
        title: "Clover (cat.svg)",
        image: "./svg/cat.svg",
        characters: ["Clover"],
        project: "Silhouette Project",
        background: "Transparent Background",
        filters: ["Safe"],
        furColor: [],
        species: ["Cat"],
        gender: ["Female"],
        bodyType: [],
        createdDate: "May 19, 2025",
        mirrors: [],
        tags: ["Vector Art", "Photopea"],
    },
    {
        id: 13,
        title: "Naori (naori1.svg)",
        image: "./svg/naori1.svg",
        characters: ["Naori"],
        project: "Silhouette Project",
        background: "Transparent Background",
        filters: ["Safe"],
        furColor: [],
        species: ["Fox"],
        gender: ["Female"],
        bodyType: [],
        createdDate: "August 4, 2025",
        mirrors: [],
        tags: ["Vector Art", "Affinity Designer 2"],
    },
    {
        id: 14,
        title: "Spencer (spencersvg.svg)",
        image: "./svg/spencersvg.svg",
        characters: ["Spencer"],
        project: "Silhouette Project",
        background: "Transparent Background",
        filters: ["Safe"],
        furColor: [],
        species: ["Fox"],
        gender: ["Male"],
        bodyType: [],
        createdDate: "July 30, 2025",
        mirrors: [],
        tags: ["Vector Art", "Affinity Designer 2"],
    },
    {
        id: 14,
        title: "Spencer (Concept A)",
        image: "./img/car/spencer.jpg",
        characters: ["Spencer"],
        project: "Untitled Project",
        background: "Purple Background",
        filters: ["Safe"],
        furColor: ["White"],
        species: ["Fox"],
        gender: ["Male"],
        bodyType: [],
        createdDate: "July 8, 2025",
        mirrors: [{ platform: "furaffinity", url: "https://www.furaffinity.net/view/61622347/"}],
        tags: ["Raster Art", "Procreate", "Purple Eyes"],
    },
    {
        id: 15,
        title: "Tail Swish Animation ",
        image: "./gif/2160.gif",
        characters: ["Sera"],
        project: "Birth by Memory",
        background: "White Background",
        filters: ["Safe"],
        furColor: ["Yellow"],
        species: ["Fox"],
        gender: ["Female"],
        bodyType: [],
        createdDate: "June 28, 2025",
        mirrors: [{ platform: "furaffinity", url: "https://www.furaffinity.net/view/61392757/"},
        { platform: "newgrounds", url: "https://www.newgrounds.com/portal/view/986507"},
        { platform: "twitter", url: "https://x.com/Xalsier/status/1939099254972166188"}],
        tags: ["Vector Art", "Affinty Designer 2", "Green Eyes", "Bra", "Animated"],
    },
    {
        id: 16,
        title: "Roxie (Concept A)",
        image: "./img/car/roxie.png",
        characters: ["Roxie"],
        project: "Untitled Project",
        background: "Gray Background",
        filters: ["Safe"],
        furColor: ["Orange"],
        species: ["Hyena"],
        gender: ["Female"],
        bodyType: ["Scars", "Spotted"],
        createdDate: "July 30, 2025",
        mirrors: [],
        tags: ["Raster Art", "Procreate"],
    },
    {
        id: 17,
        title: "Roxie (Concept B)",
        image: "./img/car/roxie2.png",
        characters: ["Roxie"],
        project: "Untitled Project",
        background: "Gray Background",
        filters: ["Safe"],
        furColor: [],
        species: ["Hyena"],
        gender: ["Female"],
        bodyType: [],
        createdDate: "August 3, 2025",
        mirrors: [],
        tags: ["Traditional Art", "Whiteboard"],
    },
    {
        id: 18,
        title: "Reindeer Base (2023)",
        image: "./img/car/reindeer.jpg",
        characters: [],
        project: null,
        background: "White Background",
        filters: ["Safe"],
        furColor: ["Gray"],
        species: ["Reindeer"],
        gender: ["Male"],
        bodyType: [],
        createdDate: "September 3, 2023",
        mirrors: [{ platform: "furaffinity", url: "https://www.furaffinity.net/view/58566530/"}],
        tags: ["Raster Art", "Procreate"],
    },
    {
        id: 19,
        title: "Bad Wolf Comic (2022)",
        image: "./img/car/witch.jpg",
        characters: [],
        project: null,
        background: "Rendered Background",
        filters: ["Safe"],
        furColor: ["Gray"],
        species: ["Cat"],
        gender: ["Male"],
        bodyType: [],
        createdDate: "September 12, 2022",
        mirrors: [{ platform: "reddit", url: "https://www.reddit.com/r/FurryArtSchool/comments/xc8mej/can_i_have_some_critique_on_the_first_page_of_a/"}],
        tags: ["Raster Art", "Clip Studio Paint", "Yellow Eyes", "Neck Collar", "Crop Top", "Witch Hat"],
    },
    {
        id: 20,
        title: "Benjamin in the Swamp (2021)",
        image: "./gif/Ben_Subu.gif",
        characters: [],
        project: null,
        background: "Rendered Background",
        filters: ["Safe"],
        furColor: ["Black"],
        species: ["Cat"],
        gender: ["Male"],
        bodyType: [],
        createdDate: "September 10, 2021",
        mirrors: [{ platform: "furaffinity", url: "https://www.furaffinity.net/view/58556403/"}],
        tags: ["Pixel Art", "Aseprite", "Yellow Eyes", "Animated"],
    },
  ]
  